// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cbdWTtxfkMN-Nz3Ro7XKo8KF-zVd-8Q',
    appId: '1:495838174621:web:1798d5f89488119659e374',
    messagingSenderId: '495838174621',
    projectId: 'flutter-application-2-b1609',
    authDomain: 'flutter-application-2-b1609.firebaseapp.com',
    storageBucket: 'flutter-application-2-b1609.appspot.com',
    measurementId: 'G-Y7M0E3SKTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkokUgvB1s_wu_Ke_qsDqvdt4YaMZ6aGQ',
    appId: '1:495838174621:android:d89bb1001a7a3a9b59e374',
    messagingSenderId: '495838174621',
    projectId: 'flutter-application-2-b1609',
    storageBucket: 'flutter-application-2-b1609.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADF0LG6Sq5FaJ6jy4j-OTHiNaaK-V2itk',
    appId: '1:495838174621:ios:b074cacfc36ebb7a59e374',
    messagingSenderId: '495838174621',
    projectId: 'flutter-application-2-b1609',
    storageBucket: 'flutter-application-2-b1609.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1cbdWTtxfkMN-Nz3Ro7XKo8KF-zVd-8Q',
    appId: '1:495838174621:web:2a9b20739ab25ec259e374',
    messagingSenderId: '495838174621',
    projectId: 'flutter-application-2-b1609',
    authDomain: 'flutter-application-2-b1609.firebaseapp.com',
    storageBucket: 'flutter-application-2-b1609.appspot.com',
    measurementId: 'G-V220F633PM',
  );
  
}
